M48
; DRILL file {KiCad 8.0.4+dfsg-1} date 2025-03-28T09:18:49+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-28T09:18:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.0272Y-1.7165
X3.0272Y-3.5669
X6.5706Y-1.7165
X6.5706Y-3.5669
M30
